# Generated by Django 5.1.6 on 2025-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_record_olingan_sana_record_qaytarish_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
